language: ruby
sudo: true
dist: xenial
rvm:
  - 2.5
python:
  - "3.1"
jdk:
  - openjdk8
before_script:
  - chmod 0755 ci/travis.rb
  - sleep 5
script:
  - ci/travis.rb
addons:
  chrome: stable
services:
  - mysql
  - xvfb
after_failure:
  - cat target/surefire-reports/*.txt
  - cat install/glassfish4/glassfish/domains/domain1/logs/*.log
cache:
  directories:
    - $HOME/.m2/repository
