ALTER TABLE `CART` ADD `FILE_COUNT` BIGINT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `CART` ADD `FILE_SIZE` BIGINT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `CARTITEM` ADD `FILE_COUNT` BIGINT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `CARTITEM` ADD `FILE_SIZE` BIGINT UNSIGNED DEFAULT 0 NOT NULL;
-- ALTER TABLE `CART` DROP COLUMN `FILE_COUNT`;
-- ALTER TABLE `CART` DROP COLUMN  `FILE_SIZE`;
-- ALTER TABLE `CARTITEM` DROP COLUMN  `FILE_COUNT`;
-- ALTER TABLE `CARTITEM` DROP COLUMN  `FILE_SIZE`;
