ALTER TABLE CART ADD FILE_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL;
ALTER TABLE CART ADD FILE_SIZE NUMBER(19, 0) DEFAULT 0 NOT NULL;
ALTER TABLE CARTITEM ADD FILE_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL;
ALTER TABLE CARTITEM ADD FILE_SIZE NUMBER(19, 0) DEFAULT 0 NOT NULL;
